version: "3"

services:
  nginx:
    image: nginx:stable
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./build:/usr/share/nginx/html/build
    ports:
      - 80:80
    restart: always

  json-server:
    image: vimagick/json-server
    command: -H 0.0.0.0 -p 3004 -w db.json
    ports:
      - "3004:3004"
    volumes:
      - ./data:/data
    restart: always
